### ISSUE TITLE
Build iOS wheels failed

### ISSUE THREAD

**Issue by mhy15287570** [freakboy3742/chaquopy#5] opened 2023-03-01 02:59 UTC
https://github.com/beeware/Python-Apple-support/issues/179

Thank you for your reply, I'm not to build a wheel for numpy, it's an example to explain what's the problem I've got.

As you said, my environment is not correctly, may be  I need to run ./make-deps.sh?   But there is no file named make-deps.sh, do you mean setup-deps?   this is my folder: 

<img width="476" alt="image" src="https://user-images.githubusercontent.com/12285275/222033171-157d4644-f6a7-4c37-b938-886b49059819.png">

**Comment by freakboy3742** [comment] 2023-03-01 03:45
My apologies - there's been a divergence between the README documentation and the required instructions. I've just pushed an update.

**Comment by mhy15287570** [comment] 2023-03-01 03:53
Thank you! I'll take a try now.

**Comment by mhy15287570** [comment] 2023-03-01 06:08
Unfortunately it went failed again. 

After i run ./setup-deps.sh , it returns some error like this:

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/12285275/222057947-1569c8dd-ceec-43b3-8f57-c5111eea6d94.png">

Here is my  folder now:
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/12285275/222058376-838ccdd7-aa09-46ce-a066-24f1615e28a8.png">

I make sure that my python version is current and had changed some code from your script, like pip -> pip3, python -> python3, but I don't know what is "wget" and how to get it. And if I run build-wheels.py, it still returns error like before which means my environment is not corrently.

So maybe the document is still a little old?

**Comment by mhy15287570** [comment] 2023-03-01 06:26
If it means the wget module for python, I have this in my environment.
<img width="523" alt="image" src="https://user-images.githubusercontent.com/12285275/222060966-3a85c52a-30bf-47a2-9070-93361542ca23.png">

**Comment by freakboy3742** [comment] 2023-03-01 06:32
[wget](https://www.gnu.org/software/wget/) is a fairly standard unix command line tool. If you don't already have it, you can get it from [homebrew](https://brew.sh).

I feel like I should warn you: Building iOS binary wheels isn't a simple task. It involves a lot of bending the internals of Python in very unusual ways, developing patches against codebases for iOS compatibility, and a deep understanding of how compilers and build chains work. 

If the cause and fix for this `wget` error wasn't obvious to you, I strongly suspect you're out of your depth. Yes, there is a gap in the documentation - it currently assumes you've got some fairly common development tools available. This is a *minor* problem compared to the issues you're going to hit building other packages. For example, building OpenCV requires a working Fortran compiler - something that the iOS toolchain doesn't provide, and neither does this repository. 

BeeWare has published binary wheels for the packages that were able to get working at the time we set up this repository. We want to support more packages, and at some point in the future, we'll revisit this repository and add more supported packages. In the meantime, if someone wants to contribute patches to this repository, I'm happy to review and potentially incorporate those patches, and publish official versions of any packages that come from those contributions.

However, I'm not in a position to provide a personalised training course teaching you how Python packages are compiled. You're more than welcome to continue experimenting if you wish, but I'm not going to be able to respond to every individual speed bump you hit along the way.

**Comment by mhy15287570** [comment] 2023-03-01 07:22
Thank you for your warning.
I'm new in linux and python but focus on iOS. I'm searching some way to run python on iOS  comfortable, have been subjective to think it can be a repository for fool. I'll continue and no more "speed bump" question.

**Closed as completed** 2023-03-01 07:23 UTC

**Comment by mhsmith** [comment] 2023-03-01 09:02
> I'm searching some way to run python on iOS comfortable

That's what Briefcase is for. If you found it "too heavy", then we'd be interested to know why. Please create an issue in the Briefcase project explaining the problems you had.
